
# ZMQ config
class ZMQConfig:
    ORDER_ROUTER_PORT = 5556
    ORDER_ROUTER_HOST = "tcp://localhost"
    ORDER_ROUTER_SOCKET_TYPE = "PULL"

    DATA_ROUTER_PUB_PORT = 5557
    DATA_ROUTER_PUB_HOST = "tcp://localhost"
    DATA_ROUTER_PUB_SOCKET_TYPE = "PUB"

    DATA_ROUTER_REP_PORT = 5558
    DATA_ROUTER_REP_HOST = "tcp://localhost"
    DATA_ROUTER_REP_SOCKET_TYPE = "REP"

    ORCHESTRATOR_OUT_PORT = 5559
    ORCHESTRATOR_OUT_HOST = "tcp://localhost"
    ORCHESTRATOR_OUT_SOCKET_TYPE = "PUB"

    ORCHESTRATOR_IN_PORT = 5560
    ORCHESTRATOR_IN_HOST = "tcp://localhost"
    ORCHESTRATOR_IN_SOCKET_TYPE = "PULL"


